apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-auth
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-auth
  template:
    metadata:
      labels:
        app: sample-auth
    spec:
      containers:
        - name: sample-auth
          image: meltaieb/sample-auth:01
          ports:
            - containerPort: 8080
          env:
            - name: CALLBACK_URL
              value: "http://mibrahim.tech"
            - name: DB_USERNAME
              value: "hamada"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
