  apiVersion: v1
  kind: Service
  metadata:
    name: sample-auth
  spec:
    type: LoadBalancer
    selector:
      app: sample-auth
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80