apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-auth
  name: sample-auth
  namespace: default
spec:
  ports:
    - nodePort: 30749
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sample-auth
  type: NodePort
