apiVersion: v1
kind: Service
metadata:
  name: sample-auth
spec:
  type: NodePort
  selector:
    matchLabels:
      app: sample-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007